/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package railway_reservation;

import javax.swing.*;
import java.sql.*;
import java.lang.*;
import java.text.SimpleDateFormat;
import javax.swing.table.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author archa
 */
public class book_ticket extends javax.swing.JFrame {
    public static int i;
    public static int seat_avail;
    /**
     * Creates new form book_ticket
     */
    public book_ticket() {
        initComponents();
        this.setLocationRelativeTo(null);
        int i=0;
        LoadStartPlace(start_place);
        LoadDestinyPlace(destiny_place1);
        pass_name.hide();
        pass_age.hide();
        pass_name1.hide();
        pass_age1.hide();
        seat_no.hide();
        seat_no1.hide();
        ph_no.hide();
        ph_no1.hide();
        submit.hide();
        ADD.setEnabled(false);
        pass_no.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void LoadStartPlace(JComboBox jComboBox1)
    {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/railway", "root", "");
            String sql="Select distinct(dplace) from train";
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            jComboBox1.removeAllItems();
            while(rs.next())
            {
                jComboBox1.addItem(rs.getString(1));
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }  
            
    }
    public void LoadDestinyPlace(JComboBox jComboBox1)
    {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/railway", "root", "");
            String sql="Select distinct(aplace) from train";
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            jComboBox1.removeAllItems();
            while(rs.next())
            {
                jComboBox1.addItem(rs.getString(1));
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }  
            
    }
    public void seat_availability(String tno)
    {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/railway", "root", "");
            String sql="SELECT `avail_seat` FROM `train` WHERE `tno` =?";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1,tno);
            ResultSet rs=pst.executeQuery();
            if(rs.next())
            {
            seat_avail=rs.getInt(1);
            }
            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        if(seat_avail>0)
        {
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/railway", "root", "");    
                String b="UPDATE `train` SET `avail_seat`=? WHERE `tno` =?";
                PreparedStatement pst=con.prepareStatement(b);
                seat_avail=seat_avail-1;
                pst.setInt(1, seat_avail);
                pst.setString(2,tno);
                pst.executeUpdate();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
        else
        {
            seat_avail=-1;
        }
    }
       
          
  
    public void reset(){
        jTable3.setModel(new DefaultTableModel(null, new String[]{"TRAIN NO.","TRAIN NAME","DEPARTURE DATE","ARRIVAL DATE","DEPARTURE TIME","ARRIVAL TIME","START PLACE","DESTINY PLACE","PRICE","SEAT_AVAIL"}));
        pass_no.setText("0");
        pass_no.setEnabled(false);
        t_no.setText("");
        t_name2.setText("");
        start_date.setDate(null);
        destiny_date1.setDate(null);
        d_time.setText("");
        a_time.setText("");
        d_place.setText("");
        a_place.setText("");
        price.setText("");
        seats_avail.setText("");    
        
        start_date.setEnabled(true);
        t_no.setEnabled(true);
        t_name.setEnabled(true);
        d_time.setEnabled(true);
        a_time.setEnabled(true);
        d_place.setEnabled(true);
        a_place.setEnabled(true);
        price.setEnabled(true);
        seats_avail.setEnabled(true);
        destiny_date1.setEnabled(true);
        
        pass_name.hide();
        pass_age.hide();
        pass_name1.hide();
        pass_age1.hide();
        seat_no.hide();
        seat_no1.hide();
        ph_no.hide();
        ph_no1.hide();
        submit.hide();    
    }
    public void search(JTable table,JComboBox dplace,JComboBox aplace,String d_date)
    {
        try{

            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/railway", "root", "");
            String sql="SELECT * FROM `train` WHERE `dplace`=? AND `aplace`=? AND `ddate`=?";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setObject(1, dplace.getSelectedItem());
            pst.setObject(2, aplace.getSelectedItem());
            pst.setString(3, d_date);
            ResultSet rs=pst.executeQuery();
            DefaultTableModel tableModel = (DefaultTableModel)table.getModel();
            Object[] row;
            int k=0;
            while(rs.next())
            {
                k=1;
                row = new Object[10];
                row[0] = rs.getString(1);
                row[1] = rs.getString(2);
                row[2] = rs.getDate(3);
                row[3] = rs.getDate(4);
                row[4] = rs.getTime(5);
                row[5] = rs.getTime(6);
                row[6] = rs.getString(7);
                row[7] = rs.getString(8);
                row[8] = rs.getInt(9);
                row[9] = rs.getInt(10);
                tableModel.addRow(row);

            }
            con.close();
            if(k==0)
            {
                JOptionPane.showMessageDialog(null, "SORRY FOR THE INCONVENIENCE!!!\n NO TRAIN IS AVAILABLE");
            }     
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        t_name = new javax.swing.JTextField();
        t_name3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        destiny_place = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        add = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t_no = new javax.swing.JTextField();
        t_name2 = new javax.swing.JTextField();
        pass_no = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        start_place = new javax.swing.JComboBox<>();
        destiny_place1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        start_date = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        destiny_date1 = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        d_time = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        a_time = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        d_place = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        a_place = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        seats_avail = new javax.swing.JTextField();
        pass_name1 = new javax.swing.JLabel();
        pass_name = new javax.swing.JTextField();
        pass_age = new javax.swing.JTextField();
        pass_age1 = new javax.swing.JLabel();
        ADD = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        home = new javax.swing.JButton();
        seat_no = new javax.swing.JLabel();
        seat_no1 = new javax.swing.JTextField();
        ph_no = new javax.swing.JLabel();
        ph_no1 = new javax.swing.JTextField();

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TRAIN NAME:");

        t_name.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        t_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nameActionPerformed(evt);
            }
        });

        t_name3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        t_name3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_name3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("DESTINY PLACE:");

        destiny_place.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        destiny_place.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destiny_placeActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TRAIN NO.", "TRAIN NAME", "DEPARTURE DATE", "ARRIVAL DATE", "DEPARTURE TIME", "ARRIVAL TIME", "START PLACE", "DESTINY PLACE", "PRICE", "SEAT_AVAIL"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TRAIN NO.", "TRAIN NAME", "DEPARTURE DATE", "ARRIVAL DATE", "DEPARTURE TIME", "ARRIVAL TIME", "START PLACE", "DESTINY PLACE", "PRICE", "SEAT_AVAIL"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        add.setBackground(new java.awt.Color(0, 102, 102));
        add.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("HOME");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("RAILWAY RESERVATION SYSTEM");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("TRAIN NUMBER:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TRAIN NAME:");

        t_no.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        t_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_noActionPerformed(evt);
            }
        });

        t_name2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        t_name2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_name2ActionPerformed(evt);
            }
        });

        pass_no.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        pass_no.setText("0");
        pass_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_noActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NUMBER OF PASSENGERS:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("START PLACE:");

        start_place.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        start_place.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_placeActionPerformed(evt);
            }
        });

        destiny_place1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        destiny_place1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destiny_place1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DESTINY  PLACE:");

        search.setBackground(new java.awt.Color(0, 102, 102));
        search.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        start_date.setDateFormatString("yyyy-MM-dd");
        start_date.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        start_date.setMaxSelectableDate(new java.util.Date(4102428676000L));
        start_date.setMinSelectableDate(new java.util.Date(1634326276000L));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DEPARTURE DATE:");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TRAIN NO.", "TRAIN NAME", "DEPARTURE DATE", "ARRIVAL DATE", "DEPARTURE TIME", "ARRIVAL TIME", "START PLACE", "DESTINY PLACE", "PRICE", "SEAT_AVAIL"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jTable3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable3KeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ARRIVAL DATE:");

        destiny_date1.setDateFormatString("yyyy-MM-dd");
        destiny_date1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DEPARTURE TIME:");

        d_time.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ARRIVAL TIME:");

        a_time.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        a_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_timeActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("DEPARTURE PLACE:");

        d_place.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("DESTINATION PLACE:");

        a_place.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("PRICE PER SEAT:");

        price.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("AVAILABLE SEATS:");

        seats_avail.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        pass_name1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        pass_name1.setForeground(new java.awt.Color(255, 255, 255));
        pass_name1.setText("PASSENGERS NAME:");

        pass_name.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        pass_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_nameActionPerformed(evt);
            }
        });

        pass_age.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        pass_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_ageActionPerformed(evt);
            }
        });

        pass_age1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        pass_age1.setForeground(new java.awt.Color(255, 255, 255));
        pass_age1.setText("PASSENGERS AGE:  ");

        ADD.setBackground(new java.awt.Color(0, 102, 102));
        ADD.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ADD.setForeground(new java.awt.Color(255, 255, 255));
        ADD.setText("ADD");
        ADD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });

        submit.setBackground(new java.awt.Color(0, 102, 102));
        submit.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("SUBMIT");
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        reset.setBackground(new java.awt.Color(0, 102, 102));
        reset.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText("RESET");
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        home.setBackground(new java.awt.Color(0, 102, 102));
        home.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        seat_no.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        seat_no.setForeground(new java.awt.Color(255, 255, 255));
        seat_no.setText("SEAT NO:  ");

        seat_no1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        seat_no1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat_no1ActionPerformed(evt);
            }
        });

        ph_no.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ph_no.setForeground(new java.awt.Color(255, 255, 255));
        ph_no.setText("PHONE NUMBER:");

        ph_no1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ph_no1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ph_no1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1009, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(t_no, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(destiny_place1, 0, 197, Short.MAX_VALUE)
                                        .addComponent(start_place, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(start_date, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(t_name2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(destiny_date1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seats_avail, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(d_time))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(a_time, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(d_place)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(a_place, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addGap(83, 83, 83)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pass_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(pass_no, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(164, 164, 164)
                                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ph_no, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ph_no1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(seat_no, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pass_age1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pass_age, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pass_name, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(seat_no1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(start_place, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(d_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(pass_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destiny_place1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(a_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ADD, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(start_date, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(d_place, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(a_place, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pass_name1)
                            .addComponent(pass_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pass_age1)
                                    .addComponent(pass_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(seat_no)
                                    .addComponent(seat_no1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(t_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ph_no)
                            .addComponent(ph_no1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t_name2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(destiny_date1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel18)
                                        .addComponent(seats_avail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_nameActionPerformed

    private void t_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_noActionPerformed

    private void t_name2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_name2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_name2ActionPerformed

    private void t_name3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_name3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_name3ActionPerformed

    private void pass_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_noActionPerformed

    private void start_placeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_placeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_start_placeActionPerformed

    private void destiny_placeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destiny_placeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destiny_placeActionPerformed

    private void destiny_place1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destiny_place1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destiny_place1ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        jTable3.setModel(new DefaultTableModel(null, new String[]{"TRAIN NO.","TRAIN NAME","DEPARTURE DATE","ARRIVAL DATE","DEPARTURE TIME","ARRIVAL TIME","START PLACE","DESTINY PLACE","PRICE","SEAT_AVAIL"}));
        if(start_date.getDate() == null||start_place.getSelectedItem().equals("")||destiny_place1.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter all details");
        }
        else {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String d_date= sdf.format(start_date.getDate());
            search(jTable3,start_place,destiny_place1,d_date);
        }

    }//GEN-LAST:event_searchActionPerformed

    private void a_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_timeActionPerformed

    private void pass_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_nameActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        DefaultTableModel d = (DefaultTableModel)jTable3.getModel();
        int selectIndex = jTable3.getSelectedRow();
        t_no.setText(d.getValueAt(selectIndex, 0).toString());
        t_name2.setText(d.getValueAt(selectIndex, 1).toString());
        java.util.Date date1;
        try {
            
            date1 = new SimpleDateFormat("yyyy-MM-dd").parse((String)d.getValueAt(selectIndex, 3).toString());
            destiny_date1.setDate(date1);
        } catch (ParseException ex) {
            Logger.getLogger(Add_train.class.getName()).log(Level.SEVERE, null, ex);
        }
        d_time.setText(d.getValueAt(selectIndex, 4).toString());
        a_time.setText(d.getValueAt(selectIndex, 5).toString());
        d_place.setText(d.getValueAt(selectIndex, 6).toString());
        a_place.setText(d.getValueAt(selectIndex, 7).toString());
        price.setText(d.getValueAt(selectIndex, 8).toString());
        seats_avail.setText(d.getValueAt(selectIndex, 9).toString());
        
        t_no.setEnabled(false);
        t_name2.setEnabled(false);
        d_time.setEnabled(false);
        a_time.setEnabled(false);
        d_place.setEnabled(false);
        a_place.setEnabled(false);
        price.setEnabled(false);
        seats_avail.setEnabled(false);
        destiny_date1.setEnabled(false);
        ADD.setEnabled(true);
        pass_no.setEnabled(true);
        
    }//GEN-LAST:event_jTable3MouseClicked

    private void pass_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_ageActionPerformed

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        System.out.println(seat_avail);    
        int passNum= Integer.parseInt(pass_no.getText());
            if(passNum<=0 )
            {
                JOptionPane.showMessageDialog(null, "KINDLY ENTER VALID NUMBER OF PASSENGERS");
            }
            else{
                if(i<passNum)
                {
                start_date.setEnabled(false);
                pass_no.setEnabled(false);
                pass_no.setEnabled(false);
                pass_name.setVisible(true);
                pass_age.setVisible(true);
                pass_name1.setVisible(true);
                pass_age1.setVisible(true);
                seat_no.setVisible(true);
                seat_no1.setVisible(true);
                ph_no.setVisible(true);
                ph_no1.setVisible(true);
                submit.setVisible(true);
                ADD.setEnabled(false);
                search.setEnabled(false);
                }
                else
                {
                    ADD.setEnabled(false);
                }

            }
    }//GEN-LAST:event_ADDActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
    int passNum= Integer.parseInt(pass_no.getText());
    int p= Integer.parseInt(price.getText());
    if(pass_name.getText().equals("") || pass_age.getText().equals("") || seat_no1.getText().equals("") || ph_no1.getText().equals(""))
    {
        JOptionPane.showMessageDialog(null, "ENTER ALL THE PASSENGER DETAILS");
    }
    else
    {
        String passName=pass_name.getText();
        String passAge=pass_age.getText();
        String Seat_no=seat_no1.getText();
        String phone_no=ph_no1.getText();
        String tno=t_no.getText();
        String tname=t_name2.getText();
        int price1= Integer.parseInt(price.getText());
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/railway", "root", "");
            String a="SELECT `seat_no` FROM `pass_list` WHERE `train_no`=? AND `train_name`=?";
            PreparedStatement b=con.prepareStatement(a);
            b.setString(1,tno);
            b.setString(2,tname);
            int flag=0,j=0;
            ResultSet c=b.executeQuery();
            String[] arr = new String[20];
            while(c.next())
            {
                arr[j]=c.getString(1);
                if(c.getString(1).equals(Seat_no))
                {
                    flag=1;
                }
                j=j+1;
            }
            if(flag==0)
            {
                    seat_availability(tno);
                    if(seat_avail>=0)
                    {
                        String sql="INSERT INTO `pass_list`(`pass_name`, `pass_age`, `seat_no`, `train_no`, `train_name`, `ph_no`) VALUES (?,?,?,?,?,?)";
                        PreparedStatement pst=con.prepareStatement(sql);
                        pst.setString(1,passName);
                        pst.setString(2,passAge);
                        pst.setString(3,Seat_no);
                        pst.setString(4,tno);
                        pst.setString(5,tname);
                        pst.setString(6,phone_no);
                        pst.executeUpdate();
                        String sql1="SELECT * FROM `pass_list` WHERE `pass_name`=? AND `pass_age`=? AND `seat_no`=? AND `train_no`=? AND `train_name`=? AND `ph_no`=?";
                        PreparedStatement pst1=con.prepareStatement(sql1);
                        pst1.setString(1,passName);
                        pst1.setString(2,passAge);
                        pst1.setString(3,Seat_no);
                        pst1.setString(4,tno);
                        pst1.setString(5,tname);
                        pst1.setString(6,phone_no);
                        ResultSet rs1=pst1.executeQuery();
                        String x = null;
                        while(rs1.next())
                        {
                            x = rs1.getString(1);
                        }
                        i=i+1;
                        JOptionPane.showMessageDialog(null,"passenger "+ i +" : Details added successfully" +"\nYOUR TICKET NUMBER IS : "+ x);   
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"SORRY !!ALL THE TICKETS ARE BOOKED AND THE TRAIN IS FULL");
                        reset();
                        search.setEnabled(true);
                        reset.setEnabled(true);
                        home.setEnabled(true);
                        i=0;
                    }
            }
            else
            {
                JOptionPane.showMessageDialog(null,"THE FOLLOWING SEATS ARE ALREADY BOOKED.\n"+Arrays.toString(arr)+"\nKINDLY SELECT ANY OTHER SEAT NUMBER FROM A1-A10 OR B1-B10 ");   
                reset.setEnabled(true);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }   

        pass_name.setText("");
        pass_age.setText("");
        seat_no1.setText("");
        ph_no1.setText("");
        ADD.setEnabled(false);
        reset.setEnabled(false);
        home.setEnabled(false);
        if(i==passNum)
        {
            int x= passNum*p;
            JOptionPane.showMessageDialog(null, "THANK YOU!!!YOU HAVE SUCCESSFULLY BOOKED "+passNum +" TICKETS \n THE TOTAL AMOUNT TO BE PAID IS : "+ x);
            reset();
            search.setEnabled(true);
            reset.setEnabled(true);
            home.setEnabled(true);
            i=0;
        }
    }
    }//GEN-LAST:event_submitActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        reset();
        ADD.setEnabled(true);
        search.setEnabled(true);
    }//GEN-LAST:event_resetActionPerformed

    private void jTable3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable3KeyPressed
        boolean a=jTable1.isEditing();
        if (a==false)
        {
            JOptionPane.showMessageDialog(null, "YOU CANNOT EDIT THE TABLE");
        }
    }//GEN-LAST:event_jTable3KeyPressed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

    }//GEN-LAST:event_addActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        this.toBack();
        setVisible(false);
        new Home().toFront();
        new Home().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_homeActionPerformed

    private void seat_no1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat_no1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat_no1ActionPerformed

    private void ph_no1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ph_no1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ph_no1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(book_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(book_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(book_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(book_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new book_ticket().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JTextField a_place;
    private javax.swing.JTextField a_time;
    public javax.swing.JButton add;
    private javax.swing.JTextField d_place;
    private javax.swing.JTextField d_time;
    private com.toedter.calendar.JDateChooser destiny_date1;
    private javax.swing.JComboBox<String> destiny_place;
    private javax.swing.JComboBox<String> destiny_place1;
    public javax.swing.JButton home;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField pass_age;
    private javax.swing.JLabel pass_age1;
    private javax.swing.JTextField pass_name;
    private javax.swing.JLabel pass_name1;
    private javax.swing.JTextField pass_no;
    private javax.swing.JLabel ph_no;
    private javax.swing.JTextField ph_no1;
    private javax.swing.JTextField price;
    private javax.swing.JButton reset;
    private javax.swing.JButton search;
    private javax.swing.JLabel seat_no;
    private javax.swing.JTextField seat_no1;
    private javax.swing.JTextField seats_avail;
    private com.toedter.calendar.JDateChooser start_date;
    private javax.swing.JComboBox<String> start_place;
    private javax.swing.JButton submit;
    private javax.swing.JTextField t_name;
    private javax.swing.JTextField t_name2;
    private javax.swing.JTextField t_name3;
    private javax.swing.JTextField t_no;
    // End of variables declaration//GEN-END:variables
}
